version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./products.json:/usr/src/app/products.json
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      dockerfile: websocket/Dockerfile
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./products.json:/usr/src/app/products.json
    depends_on:
      - api
      - websocket